### ISSUE TITLE
How is ContainerEventTest#testProcessInjectionTargetEventFiredForServlet supposed to pass?

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/cdi#623]
The CDK contains test `org.jboss.cdi.tck.tests.extensions.lifecycle.processInjectionTarget.ContainerEventTest.testProcessInjectionTargetEventFiredForServlet()`

This test that during startup a Servlet is injected.

However, there are no `load-on-startup` directives set for this Servlet, nor does the test do any request to it.

The Servlet in question contains this:

```java
@Vetoed
@WebServlet("/test")
public class TestServlet extends HttpServlet {

    private static final long serialVersionUID = -7672096092047821010L;
    private static boolean isWrappedInjectionSuccessfull = false;

    Sheep sheep;

    @Inject
    Fence fence;

    @Inject
    public void initialize(Sheep sheep) {
        this.sheep = sheep;
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    }
}
```

There is no web.xml setting `load-on-startup`.

How is this supposed to work?

/cc @scottmarlow @dmatej

**Comment by starksm64** [comment]
The doGet() method or runtime behavior is not tested. All that is tested is that the `observeServlet` method on the ProcessInjectionTargetObserver extension is fired:

```java
public class ProcessInjectionTargetObserver implements Extension {
...
    public void observeServlet(@Observes ProcessInjectionTarget<TestServlet> event, BeanManager beanManager) {
        servletEvent = event;
        System.out.printf("+++ ProcessInjectionTargetObserver.observeServlet(%s)\n", event.getInjectionTarget());
        Thread.dumpStack();
        event.setInjectionTarget(new CustomInjectionTarget<TestServlet>(event.getInjectionTarget(), () -> TestServlet.setIsWrappedInjectionSuccessfull(true)));
    }
...
```

The System.out.printf() and Thread.dumpStack() I added when running that test show the following in the WildFly log:
```
2022-06-04 12:50:20,070 INFO  [stdout] (MSC service thread 1-5) +++ ProcessInjectionTargetObserver.observeServlet(InjectionTarget for [BackedAnnotatedType] public @Vetoed @WebServlet class org.jboss.cdi.tck.tests.extensions.lifecycle.processInjectionTarget.TestServlet)
2022-06-04 12:50:20,071 ERROR [stderr] (MSC service thread 1-5) java.lang.Exception: Stack trace
2022-06-04 12:50:20,071 ERROR [stderr] (MSC service thread 1-5) 	at java.base/java.lang.Thread.dumpStack(Thread.java:1387)
2022-06-04 12:50:20,072 ERROR [stderr] (MSC service thread 1-5) 	at deployment.ContainerEventTestf998546f9cf8273184e901861ea3be7b0f93e34.war//org.jboss.cdi.tck.tests.extensions.lifecycle.processInjectionTarget.ProcessInjectionTargetObserver.observeServlet(ProcessInjectionTargetObserver.java:51)
2022-06-04 12:50:20,072 ERROR [stderr] (MSC service thread 1-5) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-06-04 12:50:20,072 ERROR [stderr] (MSC service thread 1-5) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-06-04 12:50:20,072 ERROR [stderr] (MSC service thread 1-5) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-04 12:50:20,073 ERROR [stderr] (MSC service thread 1-5) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-06-04 12:50:20,073 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
2022-06-04 12:50:20,073 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
2022-06-04 12:50:20,073 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
2022-06-04 12:50:20,074 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:126)
2022-06-04 12:50:20,074 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
2022-06-04 12:50:20,074 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
2022-06-04 12:50:20,075 ERROR [stderr] (MSC service thread 1-5) 	at jakarta.enterprise.api//jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
2022-06-04 12:50:20,075 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.util.Observers.notify(Observers.java:166)
2022-06-04 12:50:20,075 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
2022-06-04 12:50:20,075 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
2022-06-04 12:50:20,076 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
2022-06-04 12:50:20,076 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
2022-06-04 12:50:20,076 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
2022-06-04 12:50:20,076 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
2022-06-04 12:50:20,076 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.bootstrap.events.AbstractProcessInjectionTarget.fire(AbstractProcessInjectionTarget.java:40)
2022-06-04 12:50:20,077 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessInjectionTarget(ContainerLifecycleEvents.java:279)
2022-06-04 12:50:20,077 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.weld.core@5.0.0.SP1//org.jboss.weld.manager.BeanManagerImpl.fireProcessInjectionTarget(BeanManagerImpl.java:1219)
2022-06-04 12:50:20,077 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.as.weld.spi@27.0.0.Alpha1//org.jboss.as.weld.spi.ComponentSupport.processInjectionTarget(ComponentSupport.java:64)
2022-06-04 12:50:20,077 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.as.weld@27.0.0.Alpha1//org.jboss.as.weld.injection.WeldComponentService.start(WeldComponentService.java:126)
2022-06-04 12:50:20,077 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
2022-06-04 12:50:20,078 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
2022-06-04 12:50:20,078 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
2022-06-04 12:50:20,078 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2022-06-04 12:50:20,078 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
2022-06-04 12:50:20,078 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
2022-06-04 12:50:20,079 ERROR [stderr] (MSC service thread 1-5) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
2022-06-04 12:50:20,079 ERROR [stderr] (MSC service thread 1-5) 	at java.base/java.lang.Thread.run(Thread.java:834)
20
```

**Comment by arjantijms** [comment]
> All that is tested is that the observeServlet method on the ProcessInjectionTargetObserver extension is fired:

Since the Servlet itself is vetoed as a bean CDI should not scan it automatically right? So it must be the Servlet container that explicitly creates the Servlet, and explicitly calls the fire event methods.

In GlassFish, the Servlet is only created when accessed, so these explicit calls never take place during the current test.

In WildFly, this code seems to do it, but just from the stack it's not clear what makes WildFly process `TestServlet`:

https://github.com/wildfly/wildfly/blob/main/weld/subsystem/src/main/java/org/jboss/as/weld/injection/WeldComponentService.java#L126

https://github.com/wildfly/wildfly/blob/main/weld/spi/src/main/java/org/jboss/as/weld/spi/ComponentSupport.java#L64

**Comment by starksm64** [comment]
This seems to be something tests from this Jakarta EE section. @manovotn, comments about @Vetoed and EE components?

## `ProcessInjectionTarget` event and EJB

When running in Jakarta EE, the container must also fire an event for every Jakarta EE component class supporting injection that may be instantiated by the container at runtime, including every managed bean declared using `@ManagedBean`, EJB session or message-driven bean.

The container must extend the rules defined in <<process_injection_target>> for managed bean to EJB session bean and other Jakarta EE component class supporting injection.

For example, this observer decorates the `InjectionTarget` for all servlets.
[source, java]
----
<T extends Servlet> void decorateServlet(@Observes ProcessInjectionTarget<T> pit) {
    pit.setInjectionTarget( decorate( pit.getInjectionTarget() ) );
}
----

**Comment by arjantijms** [comment]
@starksm64 thanks for that text. It seems clear enough. The key phrase here is "that may be instantiated", which explains how the test is supposed to pass indeed.

Additionally I guess the decorated injection points have to be stored "somewhere" until it's time to actually instantiate the Servlet, and when that time comes, not fire the ProcessInjectionTarget event again, and re-use the previously obtained outcome (if any)?

Interesting that it looks like there's nothing in GlassFish actually trying to fire events for injection points when the servlet is not actually instantiated yet.

**Comment by manovotn** [comment]
The part Scott quoted is the correct one albeit I am not sure how is this implemented in various EE servers.

If memory serves, I think in Undertow (WFLY) I saw that all filters and servlets were automatically CDI beans which made this a lot easier to handle but I am not sure this is an option elsewhere.

> Interesting that it looks like there's nothing in GlassFish actually trying to fire events for injection points when the servlet is not actually instantiated yet.

The CDI container fires `ProcessInjectionTarget` automatically for discovered managed beans identified during type discovery - maybe you are registering the servlet as a (annotated) type somewhere?

> Additionally I guess the decorated injection points have to be stored "somewhere" until it's time to actually instantiate the Servlet, and when that time comes, not fire the ProcessInjectionTarget event again, and re-use the previously obtained outcome (if any)?

`ProcessInjectionTarget` is [fired during bean discovery](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#bean_discovery_steps) and as such will always happen prior to any CDI attempt to instantiate the bean. I don't understand how you'd fire `ProcessInjectionTarget` event again?
As for how to get/store modified PIT, the CDI container should hold that information so ideally you get it from there. I wonder if you could use something like `BeanManager.createInjectionTargetFactory()`?

**Comment by arjantijms** [comment]
>  maybe you are registering the servlet as a (annotated) type somewhere?

Nope, that would have been an explanation, but it's not happening AFAIK. 

The only thing which is happening (and as far as I can see, was ever happening), that a Servlet was created when needed using roughly the code shown below:

```java
public <T> CDIInjectionContext<T> createManagedObject(Class<T> managedClass, BundleDescriptor bundle) {
        // First get BeanDeploymentArchive
        BeanDeploymentArchiveImpl beanDeploymentArchive = getBeanDeploymentArchiveFromBundle(bundle);
        WeldManager beanManager = getWeldManagerFromBundle(bundle, beanDeploymentArchive);

        AnnotatedType annotatedType = beanManager.createAnnotatedType(managedClass);

        InjectionTarget injectionTarget = beanDeploymentArchive.getInjectionTarget(annotatedType);
        if (injectionTarget == null) {
            injectionTarget = beanManager.fireProcessInjectionTarget(annotatedType);
        }

        CreationalContext creationalContext = beanManager.createCreationalContext(null);

        Object managedObject = injectionTarget.produce(creationalContext);

        injectionTarget.inject(managedObject, creationalContext);
        injectionTarget.postConstruct(managedObject);
        
        return new CDIInjectionContextImpl(injectionTarget, creationalContext, managedObject);
 }
```

I've now worked around this by creating Servlets eagerly despite them being set to "load-on-startup" or not, but as said it's remarkable that this passed before somehow (with Weld 4 / GF 6).

**Comment by manovotn** [comment]
Then I afraid I am out of ideas here.

The code you posted seems fine so long as it gets invoked early - I suppose that for some reason this must have been invoked eagerly in GF with Weld 4? Probably by some coincidence? You'd need to debug that piece of code with GF 6 and the very same TCK test to see.

**Comment by arjantijms** [comment]
> I suppose that for some reason this must have been invoked eagerly in GF with Weld 4

As far as I can see nothing changed there; it was only ever invoked at runtime when a Servlet was invoked. But indeed, I need the debug on GF 6 with the same test. I'll close the issue then. Thanks!

**Comment by Pandrex247** [comment]
@arjantijms just in case you decide to come back to it.

The code is slightly different now between Payara and GlassFish, but I suspect the cause will be the same.
In Payara at least this test now fails as a knock-on effect from the change of the bean discovery mode.

At [this point](https://github.com/eclipse-ee4j/glassfish/blob/7.0.0-M6/appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java#L380) on CDI 3 this evaluates to true, on CDI 4 it evaluates to false.
The effect of this is that [here](https://github.com/eclipse-ee4j/glassfish/blob/7.0.0-M6/appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java#L423) the if check fails on CDI 4, and so the servlet isn't registered as a bean.
As the application gets loaded, [PITs are only fired for bean classes](https://github.com/eclipse-ee4j/glassfish/blob/7.0.0-M6/appserver/web/weld-integration/src/main/java/org/glassfish/weld/WeldDeployer.java#L589).

**Comment by arjantijms** [comment]
@Pandrex247 Thanks for your sharp analysis there. Comparing to GF 6/CDI 3 to find out what changed was on my list, but I indeed hadn't come back to it.

It looks like the previous behaviour was in a certain way a side-effect of registering everything as a bean in the first place. As the Servlet is explicitly vetoed, it shouldn't have worked previously (maybe we need to check ourselves for the @Vetoed annotation).

Following that, and the reason why I didn't just fire the event to satisfy the CDI TCK, is that when somebody actually does something in the event (replace the inject target), it would not take effect. The "problem" in GlassFish (and as a result Payara) is that the Servlet isn't actually a CDI bean, but a more manually created "injected Jakarta EE component". 

This is according to the specifications, but it makes all of this a bit more difficult.

If you consider the code I quoted above again:

```java
public <T> CDIInjectionContext<T> createManagedObject(Class<T> managedClass, BundleDescriptor bundle, boolean invokePostConstruct) {
        // First get BeanDeploymentArchive
        BeanDeploymentArchiveImpl beanDeploymentArchive = getBeanDeploymentArchiveFromBundle(bundle);
        WeldManager beanManager = getWeldManagerFromBundle(bundle, beanDeploymentArchive);

        AnnotatedType annotatedType = beanManager.createAnnotatedType(managedClass);
        if (!invokePostConstruct) {
            annotatedType = new NoPostConstructPreDestroyAnnotatedType(annotatedType);
        }

        InjectionTarget injectionTarget = beanDeploymentArchive.getInjectionTarget(annotatedType);
        if (injectionTarget == null) {
            injectionTarget = beanManager.fireProcessInjectionTarget(annotatedType);
        }

        CreationalContext creationalContext = beanManager.createCreationalContext(null);

        Object managedObject = injectionTarget.produce(creationalContext);

        injectionTarget.inject(managedObject, creationalContext);

        if (invokePostConstruct) {
            injectionTarget.postConstruct(managedObject);
        }

        return new CDIInjectionContextImpl(injectionTarget, creationalContext, managedObject);
    }
```

Then I *think* the injection target obtained by this line:

```
injectionTarget = beanManager.fireProcessInjectionTarget(annotatedType);
```

Should be stored and used when the Servlet is actually created. Otherwise the event would fire twice for each Servlet, and the result of the first event would just be lost.

Probably the best thing would be to standardise the approach taken by WildFly, and make a Servlet an actual bean, and then later on also obtain it as an actual bean (without the manual CDI simulating code that there's now). I've discussed this with the Servlet spec team before, but it didn't make it in yet (Red Hat was supportive though).

@manovotn What do you think?

**Comment by manovotn** [comment]
> make a Servlet an actual bean, and then later on also obtain it as an actual bean

Yeah this is what we discussed in the CDI meeting (if I remember correctly?) and I am still in favor of it.
It is basically the most "natural" way of integrating it since everything else will be a sort of hack to still have it as injection target while not considering it an actual bean.

> Otherwise the event would fire twice for each Servlet, and the result of the first event would just be lost.

Why was the first event fired in this case? 
The `beanManager.fireProcessInjectionTarget(annotatedType);` returns you an injection target after all modifications from extension. So in theory, if you make sure this is the only event fired for that type, it should work.
